### ISSUE TITLE
yaml-file opening closes comment window before comment has been made.

### ISSUE THREAD

**Issue by zbloff** [phenopype/phenopype#2]
This triggers if the order of windows opening between the yaml-editor and the image window happens in a certain way.
speifically:
1. image-window with comment opens first
2. yaml-editor opens second. This causes the image window to close and then reopen. If you were about to write a comment, upon reopening the comment is considered done.
I.e. If edit=false, you are now unable to enter a comment without changing to edit=true in the yaml-file.

I'm running this in a virtual windows environment that is pretty slow. It might not affect users running phenopype natively.

**Comment by mluerig** [comment]
this should have been fixed with https://github.com/phenopype/phenopype/releases/tag/5.0.0
