### ISSUE TITLE
no able to get images from gallery

### ISSUE THREAD

**Issue by JaimeMAnayaRojas** [phenopype/phenopype#3]
Hi Moritz, two things form Project 6.

1. proj = pp.Project("project") should be replace for proj = pp.project("project") in the documentation
2. I have got a problem getting the images for the example.
## add the two snail-images from the data folder
proj.add_files(image_dir = r"../../gallery/data", include="snails")

show I get them from the main phenopype repo (I don't find them) or are they in a hidden folder during the installation? because I can't find them

Thanks

**Comment by mluerig** [comment]
thanks Jaime for reporting this 

> I have got a problem getting the images for the example.
I decluttered that preparatory/import cell so it hopefully is more clear now: the images are in the data folder, you just need to point to it when importing.

> proj = pp.Project("project") should be replace for proj = pp.project("project") in the documentation
where did you see `pp.project`? in the gallery it was already `Project` (how it should be)...

I gave it a try with phenopype v3.3.2 and everything works. would be great of you could give me a quick feedback if it works on your end as well
